[build]
  command = "npm run build -- --configuration=production"
  publish = "dist/frontend"
  environment = { API_BASE_URL = "https://greenhalo.onrender.com" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200